import {
  Router,
  Request,
  Response,
} from "express";

import { pool } from "../config/db.js";

const router = Router();

/* =========================================================
   FIND VALID SUCCESS PAYMENT STATUS

   The payments table has its own CHECK constraint.
   We detect the actual successful status allowed by DB
   instead of hard-coding "SUCCESS".
========================================================= */

async function getSuccessfulPaymentStatus(
  client: any
): Promise<string> {
  const result =
    await client.query(
      `
      SELECT
        pg_get_constraintdef(oid) AS definition
      FROM pg_constraint
      WHERE
        conname = 'payments_status_check'
        AND conrelid = 'payments'::regclass
      LIMIT 1
      `
    );

  if (
    result.rowCount === 0
  ) {
    throw new Error(
      "payments_status_check constraint was not found."
    );
  }

  const definition =
    String(
      result.rows[0].definition
    );

  const matches =
    definition.match(
      /'([^']+)'/g
    ) || [];

  const allowedStatuses =
    matches.map(
      (value: string) =>
        value.substring(
          1,
          value.length - 1
        )
    );

  const preferredStatuses = [
    "SUCCESS",
    "COMPLETED",
    "PAID",
    "RECEIVED",
  ];

  const successfulStatus =
    preferredStatuses.find(
      (status) =>
        allowedStatuses.includes(
          status
        )
    );

  if (
    successfulStatus
  ) {
    return successfulStatus;
  }

  throw new Error(
    `No successful payment status was found in payments_status_check. Allowed statuses: ${allowedStatuses.join(", ")}`
  );
}

/* =========================================================
   CREATE INVOICE
   POST /api/invoices
========================================================= */

router.post(
  "/",
  async (
    req: Request,
    res: Response
  ) => {
    const client =
      await pool.connect();

    try {
      const {
        booking_id,
        payment_id,
        invoice_type,
        invoice_date,
        amount,
        generated_by,
      } = req.body;

      /* -----------------------------------------------------
         BASIC VALIDATION
      ----------------------------------------------------- */

      if (!booking_id) {
        return res.status(400).json({
          success: false,
          message:
            "Booking ID is required.",
        });
      }

      if (!payment_id) {
        return res.status(400).json({
          success: false,
          message:
            "Payment ID is required.",
        });
      }

      if (!invoice_type) {
        return res.status(400).json({
          success: false,
          message:
            "Invoice type is required.",
        });
      }

      if (
        ![
          "CASH_MEMO",
          "CREDIT_MEMO",
        ].includes(
          invoice_type
        )
      ) {
        return res.status(400).json({
          success: false,
          message:
            "Invoice type must be CASH_MEMO or CREDIT_MEMO.",
        });
      }

      if (!invoice_date) {
        return res.status(400).json({
          success: false,
          message:
            "Invoice date is required.",
        });
      }

      const invoiceAmount =
        Number(amount);

      if (
        !Number.isFinite(
          invoiceAmount
        ) ||
        invoiceAmount <= 0
      ) {
        return res.status(400).json({
          success: false,
          message:
            "Invoice amount must be greater than zero.",
        });
      }

      if (!generated_by) {
        return res.status(400).json({
          success: false,
          message:
            "Generated by user ID is required.",
        });
      }

      /* -----------------------------------------------------
         TRANSACTION START
      ----------------------------------------------------- */

      await client.query(
        "BEGIN"
      );

      /* -----------------------------------------------------
         GET SUCCESSFUL PAYMENT STATUS
      ----------------------------------------------------- */

      const successfulPaymentStatus =
        await getSuccessfulPaymentStatus(
          client
        );

      /* -----------------------------------------------------
         VERIFY USER
      ----------------------------------------------------- */

      const userResult =
        await client.query(
          `
          SELECT
            id,
            full_name,
            username,
            is_active
          FROM users
          WHERE id = $1
          LIMIT 1
          `,
          [generated_by]
        );

      if (
        userResult.rowCount === 0
      ) {
        throw new Error(
          "Invoice generating user was not found."
        );
      }

      if (
        !userResult.rows[0]
          .is_active
      ) {
        throw new Error(
          "Invoice generating user is inactive."
        );
      }

      /* -----------------------------------------------------
         VERIFY BOOKING
      ----------------------------------------------------- */

      const bookingResult =
        await client.query(
          `
          SELECT
            id,
            booking_reference,
            booking_status,
            approval_status,
            acceptance_status
          FROM bookings
          WHERE id = $1
          FOR UPDATE
          `,
          [booking_id]
        );

      if (
        bookingResult.rowCount === 0
      ) {
        throw new Error(
          "Booking not found."
        );
      }

      const booking =
        bookingResult.rows[0];

      /* -----------------------------------------------------
         APPROVAL CHECK
      ----------------------------------------------------- */

      if (
        booking.approval_status !==
        "APPROVED"
      ) {
        throw new Error(
          "Invoice cannot be generated before booking approval."
        );
      }

      /* -----------------------------------------------------
         ACCEPTANCE CHECK
      ----------------------------------------------------- */

      if (
        booking.acceptance_status !==
        "ACCEPTED"
      ) {
        throw new Error(
          "Invoice cannot be generated before room acceptance."
        );
      }

      /* -----------------------------------------------------
         VERIFY PAYMENT
      ----------------------------------------------------- */

      const paymentResult =
        await client.query(
          `
          SELECT
            id,
            booking_id,
            amount,
            payment_method,
            transaction_number,
            payment_date,
            payment_status,
            received_by
          FROM payments
          WHERE
            id = $1
            AND booking_id = $2
          FOR UPDATE
          `,
          [
            payment_id,
            booking_id,
          ]
        );

      if (
        paymentResult.rowCount === 0
      ) {
        throw new Error(
          "Payment record was not found for this booking."
        );
      }

      const payment =
        paymentResult.rows[0];

      /* -----------------------------------------------------
         PAYMENT STATUS CHECK

         IMPORTANT:
         Do NOT hard-code SUCCESS.
         Compare with actual DB-allowed successful status.
      ----------------------------------------------------- */

      if (
        payment.payment_status !==
        successfulPaymentStatus
      ) {
        throw new Error(
          `Invoice can only be generated for a successful payment. Current payment status: ${payment.payment_status}`
        );
      }

      /* -----------------------------------------------------
         VERIFY AMOUNT
      ----------------------------------------------------- */

      const paymentAmount =
        Number(
          payment.amount
        );

      if (
        !Number.isFinite(
          paymentAmount
        ) ||
        paymentAmount <= 0
      ) {
        throw new Error(
          "Recorded payment amount is invalid."
        );
      }

      if (
        invoiceAmount >
        paymentAmount
      ) {
        throw new Error(
          "Invoice amount cannot be greater than the recorded payment amount."
        );
      }

      /* -----------------------------------------------------
         CHECK DUPLICATE PAYMENT INVOICE
      ----------------------------------------------------- */

      const paymentInvoiceResult =
        await client.query(
          `
          SELECT
            id,
            invoice_number,
            invoice_type,
            amount
          FROM booking_invoices
          WHERE payment_id = $1
          LIMIT 1
          `,
          [payment_id]
        );

      if (
        (
          paymentInvoiceResult
            .rowCount ?? 0
        ) > 0
      ) {
        await client.query(
          "ROLLBACK"
        );

        return res.status(409).json({
          success: false,
          message:
            "An invoice has already been generated for this payment.",
          invoice:
            paymentInvoiceResult
              .rows[0],
        });
      }

      /* -----------------------------------------------------
         GENERATE INVOICE NUMBER
      ----------------------------------------------------- */

      const invoiceNumberResult =
        await client.query(
          `
          SELECT public.generate_invoice_number(
            $1::DATE
          ) AS invoice_number
          `,
          [invoice_date]
        );

      const invoiceNumber =
        invoiceNumberResult.rows[0]?.invoice_number;

      if (
        typeof invoiceNumber !== "string" ||
        !/^\d{8}$/.test(invoiceNumber)
      ) {
        throw new Error(
          "The database did not return a valid generated invoice number."
        );
      }

      /* -----------------------------------------------------
         INSERT INVOICE
      ----------------------------------------------------- */

      const invoiceResult =
        await client.query(
          `
          INSERT INTO booking_invoices (
            booking_id,
            invoice_number,
            invoice_type,
            invoice_date,
            amount,
            payment_id,
            generated_by
          )
          VALUES (
            $1,
            $2,
            $3,
            $4,
            $5,
            $6,
            $7
          )
          RETURNING
            id,
            booking_id,
            invoice_number,
            invoice_type,
            invoice_date,
            amount,
            payment_id,
            generated_by,
            created_at
          `,
          [
            booking_id,
            invoiceNumber,
            invoice_type,
            invoice_date,
            invoiceAmount,
            payment_id,
            generated_by,
          ]
        );

      const invoice =
        invoiceResult.rows[0];

      /* -----------------------------------------------------
         COMMIT
      ----------------------------------------------------- */

      await client.query(
        "COMMIT"
      );

      return res.status(201).json({
        success: true,

        message:
          "Invoice generated successfully.",

        invoice,

        booking: {
          id:
            booking.id,

          booking_reference:
            booking.booking_reference,
        },

        payment: {
          id:
            payment.id,

          amount:
            paymentAmount,

          payment_method:
            payment.payment_method,

          transaction_number:
            payment.transaction_number,

          payment_date:
            payment.payment_date,

          payment_status:
            payment.payment_status,
        },

        next_stage:
          "ROOM_LOCKED",
      });
    } catch (error) {
      try {
        await client.query(
          "ROLLBACK"
        );
      } catch {
        // Ignore rollback errors
      }

      console.error(
        "Invoice generation error:",
        error
      );

      return res.status(400).json({
        success: false,
        message:
          error instanceof Error
            ? error.message
            : "Unable to generate invoice.",
      });
    } finally {
      client.release();
    }
  }
);

/* =========================================================
   GET INVOICES FOR BOOKING
   GET /api/invoices/booking/:bookingId
========================================================= */

router.get(
  "/booking/:bookingId",
  async (
    req: Request,
    res: Response
  ) => {
    try {
      const bookingId =
        String(
          req.params.bookingId
        );

      const result =
        await pool.query(
          `
          SELECT
            bi.id,
            bi.booking_id,
            bi.invoice_number,
            bi.invoice_type,
            bi.invoice_date,
            bi.amount,
            bi.payment_id,
            bi.generated_by,
            bi.created_at,

            p.payment_method,
            p.transaction_number,
            p.payment_date,
            p.payment_status,

            u.full_name AS generated_by_name

          FROM booking_invoices bi

          LEFT JOIN payments p
            ON p.id = bi.payment_id

          LEFT JOIN users u
            ON u.id = bi.generated_by

          WHERE
            bi.booking_id = $1

          ORDER BY
            bi.created_at DESC
          `,
          [bookingId]
        );

      return res.json({
        success: true,
        invoices:
          result.rows,
      });
    } catch (error) {
      console.error(
        "Get booking invoices error:",
        error
      );

      return res.status(500).json({
        success: false,
        message:
          "Unable to fetch booking invoices.",
      });
    }
  }
);

/* =========================================================
   GET SINGLE INVOICE
   GET /api/invoices/:id
========================================================= */

router.get(
  "/:id",
  async (
    req: Request,
    res: Response
  ) => {
    try {
      const invoiceId =
        String(
          req.params.id
        );

      const result =
        await pool.query(
          `
          SELECT
            bi.id,
            bi.booking_id,
            bi.invoice_number,
            bi.invoice_type,
            bi.invoice_date,
            bi.amount,
            bi.payment_id,
            bi.generated_by,
            bi.created_at,

            p.payment_method,
            p.transaction_number,
            p.payment_date,
            p.payment_status,

            u.full_name AS generated_by_name

          FROM booking_invoices bi

          LEFT JOIN payments p
            ON p.id = bi.payment_id

          LEFT JOIN users u
            ON u.id = bi.generated_by

          WHERE
            bi.id = $1

          LIMIT 1
          `,
          [invoiceId]
        );

      if (
        result.rowCount === 0
      ) {
        return res.status(404).json({
          success: false,
          message:
            "Invoice not found.",
        });
      }

      return res.json({
        success: true,
        invoice:
          result.rows[0],
      });
    } catch (error) {
      console.error(
        "Get invoice error:",
        error
      );

      return res.status(500).json({
        success: false,
        message:
          "Unable to fetch invoice.",
      });
    }
  }
);

export default router;